<?php


function Create_Site_Info_menu() {
    $items = array();
    $items['site/siteinfos'] = array(
    'title' => 'Create site_info nodes.',
        'page callback' => 'show_page',
        'access arguments' => array('view own profile'), // permission
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

function show_page(){
    $content = '';
    $handle = opendir("/var/www/html/faculty_sites");
    while (false !== ($entry = readdir($handle))) {
        if($entry != '.' && $entry != '..'){
            $node = new stdClass();
            $node->type = 'site_info';
            node_object_prepare($node);
            $node->title = $entry;
            $node->field_site_name[LANGUAGE_NONE]['0']['url'] = $entry;
            $node->field_site_name[LANGUAGE_NONE]['0']['title'] = $entry;
            $node->field_ucm_site_description[LANGUAGE_NONE]['0']['value'] = $entry . "'s Website";
            node_save($node);
        }
        
    }
    return $content;
}
?>
