<?php


function Create_Site_Info_menu() {
    $items['site/siteinfos'] = array(
    'title' => 'Create site_info nodes.',
        'page callback' => 'show_page',
  );

  return $items;
}

function show_page(){
    $content = '';
    $handle = opendir("/var/www/html/faculty_sites");
    while (false !== ($entry = readdir($handle))) {
        $content .= "$entry<br/>\n";
    }
    return $content;
}
?>
