<?php
function SiteList_preprocess_page(&$variables) {

drupal_add_css(drupal_get_path('module', 'SiteList') .'./smoothness/styles.css');
//drupal_add_js(drupal_get_path('module', 'SiteList') .'/DataTables/media/js/jquery.js');
//drupal_add_js(drupal_get_path('module', 'SiteList') .'/DataTables/media/js/jquery.dataTables.js');
//drupal_add_js(drupal_get_path('module', 'SiteList') .'/DataTables/media/js/table_init.js');

}


function SiteList_help($path, $arg){
if($path == 'admin/help#SiteList'){
return t('Display a list of websites hosted at faculty.ucmerced.edu');
}
}

function SiteList_block_info(){
$blocks = array();
$blocks['site_list'] = array(
'info' => t('Display a list of websites hosted at faculty.ucmerced.edu.'),
'cache' => DRUPAL_NO_CACHE,
);
return $blocks;
}

function SiteList_block_view($block_name = ''){
   // drupal_add_js

if ($block_name == 'site_list'){
    $rows = array();
    $content = '<h2>Website Directory</h2><br/>';
    $query = db_select('field_data_field_ucm_site_description', 'd');
    $query->join('field_data_field_site_name', 'n', 'd.entity_id = n.entity_id');
    $query->fields('d', array('field_ucm_site_description_value'))
          ->fields('n', array('field_site_name_title', 'field_site_name_url'))
          ->orderBy('field_site_name_title', 'ASC');
    $result = $query->execute();

    while($record = $result->fetchAssoc()){

        $field1 = '<a href="' . $record['field_site_name_url'] . '">' . $record['field_site_name_title'] . '</a>';
        $field2 = $record['field_ucm_site_description_value'];
        array_push($rows, array($field1, $field2));
    }
    
    // Table settings.
$attributes['datatable_options'] = array(
  'bFilter'   => TRUE,
  'bInfo'     => TRUE,
  'bJQueryUI' => TRUE,
  'iDisplayLength' => 20,
    'bPaginate' => FALSE,
    'bAutoWidth' => TRUE,
);
// Define table columns
$header = array(
  array(
    'data' => t('Faculty Member'),
    'datatable_options' => array(
      'bSortable' => TRUE,
      'bSearchable' => TRUE,
    ),
  ),
  array(
    'data' => t('School'),
    'datatable_options' => array(
      'bSortable' => TRUE,
      'bSearchable' => TRUE,
    ),
  ),
);
 
// Render using Drupal's render API.
$build['datatable'] = array(
  '#theme' => 'datatable',
  '#header' => $header,
  '#rows' => $rows,
  '#attributes' => $attributes,
);
 
// Or, render using a theme function.
$variables = array(
  'attributes' => $attributes,
  'header' => $header,
  'rows' => $rows,
);
$content .= theme('datatable', $variables);

    $block = array (
    'content' => $content,
    );

    return $block;

    }
}
?>
